console.log(1 + "2");
console.log("1" + 2);
console.log("1" + "2");
console.log(2 - "1");
console.log(+"2" + +"2");
console.log(6 / "3");
console.log(+true);
console.log(+"");
console.log(null > 0);
console.log(null < 0);
console.log(null >= 0);
console.log(null == 0);
console.log(typeof null);
const age = null;
const a = Number(age);
console.log(a);
let counter = 1;
let b = ++counter;
console.log(b);
let counter1 = 1;
let c = counter1++;
console.log(c);
